### ISSUE TITLE
Is there a plan to update the release?

### ISSUE THREAD

**Issue by zarif98** [Mimer29or40/pythonnet-stubs#1]
The code has been updated 6 months ago but the release is still back in 2022. Could we see an updated release that we can run?

**Comment by Mimer29or40** [comment]
Honestly, I thought I did when I made those changes, I built it but never uploaded them. This is mostly for an internal library that I maintain at my job, so I did not think anyone would actually use it. I'll upload a release when I get a chance to tomorrow.

**Comment by zarif98** [comment]
Please do! I'm trying to create a stub generator for my codebase as well since our Python code interfaces with our C# code and yours seem to handle a lot. Would you be able to update the readme as well? Kinda confused on how to run this.

**Comment by Mimer29or40** [comment]
Release updated
